import { useExecutionStore } from "../store/execution-store.js";
import { useAgentStore } from "../store/agent-store.js";

export function useAppStoreBindings() {
  return {
    runtime: useAgentStore((state) => state.runtime),
    session: useAgentStore((state) => state.session),
    input: useAgentStore((state) => state.input),
    messages: useAgentStore((state) => state.messages),
    activities: useAgentStore((state) => state.activities),
    streaming: useAgentStore((state) => state.streaming),
    assistantDraft: useAgentStore((state) => state.assistantDraft),
    status: useAgentStore((state) => state.status),
    notice: useAgentStore((state) => state.notice),
    error: useAgentStore((state) => state.error),
    viewMode: useAgentStore((state) => state.viewMode),
    selectedSessionIndex: useAgentStore((state) => state.selectedSessionIndex),
    vimMode: useAgentStore((state) => state.vimMode),
    cursorOffset: useAgentStore((state) => state.cursorOffset),
    sidebarTab: useAgentStore((state) => state.sidebarTab),
    activeModal: useAgentStore((state) => state.activeModal),
    agentMode: useAgentStore((state) => state.agentMode),
    showInputPreview: useAgentStore((state) => state.showInputPreview),
    pendingInput: useAgentStore((state) => state.pendingInput),
    currentPlan: useAgentStore((state) => state.currentPlan),
    taskBuffers: useAgentStore((state) => state.taskBuffers),
    toolCalls: useAgentStore((state) => state.toolCalls),
    toolExecuting: useAgentStore((state) => state.toolExecuting),
    phase: useAgentStore((state) => state.phase),
    iteration: useAgentStore((state) => state.iteration),
    recentModels: useAgentStore((state) => state.recentModels),
    telemetryExportStatus: useAgentStore((state) => state.telemetryExportStatus),
    lastExportPath: useAgentStore((state) => state.lastExportPath),
    slashMenuDismissed: useAgentStore((state) => state.slashMenuDismissed),
    selectedSlashCommandIndex: useAgentStore((state) => state.selectedSlashCommandIndex),
    showHistorySearch: useAgentStore((state) => state.showHistorySearch),
    detailContent: useAgentStore((state) => state.detailContent),
    setRuntime: useAgentStore((state) => state.setRuntime),
    setSession: useAgentStore((state) => state.setSession),
    setInput: useAgentStore((state) => state.setInput),
    setMessages: useAgentStore((state) => state.setMessages),
    setActivities: useAgentStore((state) => state.setActivities),
    setStatus: useAgentStore((state) => state.setStatus),
    setNotice: useAgentStore((state) => state.setNotice),
    setError: useAgentStore((state) => state.setError),
    setViewMode: useAgentStore((state) => state.setViewMode),
    setVimMode: useAgentStore((state) => state.setVimMode),
    setSidebarTab: useAgentStore((state) => state.setSidebarTab),
    setActiveModal: useAgentStore((state) => state.setActiveModal),
    setAgentMode: useAgentStore((state) => state.setAgentMode),
    setShowInputPreview: useAgentStore((state) => state.setShowInputPreview),
    setPendingInput: useAgentStore((state) => state.setPendingInput),
    setCurrentPlan: useAgentStore((state) => state.setCurrentPlan),
    setToolCalls: useAgentStore((state) => state.setToolCalls),
    setRecentModels: useAgentStore((state) => state.setRecentModels),
    setTelemetryExportStatus: useAgentStore((state) => state.setTelemetryExportStatus),
    setLastExportPath: useAgentStore((state) => state.setLastExportPath),
    setShowHistorySearch: useAgentStore((state) => state.setShowHistorySearch),
    setDetailContent: useAgentStore((state) => state.setDetailContent),
    dispatch: useAgentStore((state) => state.dispatch),
    executionTasks: useExecutionStore((state) => state.tasks),
  };
}
